import type { Listing } from './types';

const now = new Date().toISOString();

export const SEED_LISTINGS: Listing[] = [
  {
    id: 1,
    slug: 'pawfect-mobile-grooming-houston',
    name: 'Pawfect Mobile Grooming',
    full_address: '4521 Westheimer Rd, Houston, TX 77027',
    city: 'Houston',
    state: 'TX',
    zip: '77027',
    phone: '(713) 555-0142',
    website: 'https://pawfectmobilegrooming.example.com',
    rating: 4.9,
    reviews_count: 187,
    google_maps_url: null,
    classification: 'mobile_pet_grooming',
    verification_confidence: 0.95,
    svc_full_groom: true,
    svc_bath_only: true,
    svc_nail_trim: true,
    svc_deshedding: true,
    svc_teeth_brushing: true,
    svc_ear_cleaning: true,
    svc_flea_treatment: false,
    svc_puppy_groom: true,
    svc_senior_groom: true,
    svc_dematting: true,
    svc_breed_cuts: true,
    accepts_dogs: true,
    accepts_cats: true,
    breed_sizes: ['small', 'medium', 'large'],
    price_range_low: 55,
    price_range_high: 120,
    is_licensed: true,
    is_insured: true,
    fear_free_certified: true,
    years_experience: 12,
    uses_natural_products: true,
    cage_free: true,
    one_on_one_attention: true,
    online_booking: true,
    image_url: null,
    image_description: null,
    primary_city: 'Houston',
    service_cities: ['Houston', 'Katy', 'Sugar Land', 'The Woodlands'],
    service_radius_miles: 25,
    created_at: now,
    updated_at: now,
  },
  {
    id: 2,
    slug: 'austin-paws-on-wheels',
    name: 'Austin Paws on Wheels',
    full_address: '1200 S Lamar Blvd, Austin, TX 78704',
    city: 'Austin',
    state: 'TX',
    zip: '78704',
    phone: '(512) 555-0298',
    website: 'https://austinpawsonwheels.example.com',
    rating: 4.7,
    reviews_count: 134,
    google_maps_url: null,
    classification: 'mobile_pet_grooming',
    verification_confidence: 0.92,
    svc_full_groom: true,
    svc_bath_only: true,
    svc_nail_trim: true,
    svc_deshedding: true,
    svc_teeth_brushing: false,
    svc_ear_cleaning: true,
    svc_flea_treatment: true,
    svc_puppy_groom: true,
    svc_senior_groom: false,
    svc_dematting: false,
    svc_breed_cuts: true,
    accepts_dogs: true,
    accepts_cats: false,
    breed_sizes: ['small', 'medium', 'large', 'giant'],
    price_range_low: 45,
    price_range_high: 110,
    is_licensed: true,
    is_insured: true,
    fear_free_certified: false,
    years_experience: 8,
    uses_natural_products: false,
    cage_free: true,
    one_on_one_attention: true,
    online_booking: true,
    image_url: null,
    image_description: null,
    primary_city: 'Austin',
    service_cities: ['Austin', 'Round Rock', 'Cedar Park'],
    service_radius_miles: 20,
    created_at: now,
    updated_at: now,
  },
  {
    id: 3,
    slug: 'sunny-paws-mobile-spa-los-angeles',
    name: 'Sunny Paws Mobile Spa',
    full_address: '8833 W Sunset Blvd, Los Angeles, CA 90069',
    city: 'Los Angeles',
    state: 'CA',
    zip: '90069',
    phone: '(310) 555-0173',
    website: 'https://sunnypawsmobilespa.example.com',
    rating: 4.8,
    reviews_count: 256,
    google_maps_url: null,
    classification: 'mobile_pet_grooming',
    verification_confidence: 0.97,
    svc_full_groom: true,
    svc_bath_only: true,
    svc_nail_trim: true,
    svc_deshedding: true,
    svc_teeth_brushing: true,
    svc_ear_cleaning: true,
    svc_flea_treatment: true,
    svc_puppy_groom: true,
    svc_senior_groom: true,
    svc_dematting: true,
    svc_breed_cuts: true,
    accepts_dogs: true,
    accepts_cats: true,
    breed_sizes: ['small', 'medium', 'large'],
    price_range_low: 75,
    price_range_high: 160,
    is_licensed: true,
    is_insured: true,
    fear_free_certified: true,
    years_experience: 15,
    uses_natural_products: true,
    cage_free: true,
    one_on_one_attention: true,
    online_booking: true,
    image_url: null,
    image_description: null,
    primary_city: 'Los Angeles',
    service_cities: ['Los Angeles', 'Santa Monica', 'Beverly Hills', 'West Hollywood'],
    service_radius_miles: 15,
    created_at: now,
    updated_at: now,
  },
  {
    id: 4,
    slug: 'san-diego-mobile-pet-care',
    name: 'San Diego Mobile Pet Care',
    full_address: '3120 University Ave, San Diego, CA 92104',
    city: 'San Diego',
    state: 'CA',
    zip: '92104',
    phone: '(619) 555-0385',
    website: null,
    rating: 4.5,
    reviews_count: 89,
    google_maps_url: null,
    classification: 'mobile_pet_grooming',
    verification_confidence: 0.88,
    svc_full_groom: true,
    svc_bath_only: true,
    svc_nail_trim: true,
    svc_deshedding: false,
    svc_teeth_brushing: false,
    svc_ear_cleaning: true,
    svc_flea_treatment: false,
    svc_puppy_groom: true,
    svc_senior_groom: true,
    svc_dematting: false,
    svc_breed_cuts: false,
    accepts_dogs: true,
    accepts_cats: true,
    breed_sizes: ['small', 'medium'],
    price_range_low: 40,
    price_range_high: 90,
    is_licensed: true,
    is_insured: false,
    fear_free_certified: false,
    years_experience: 5,
    uses_natural_products: true,
    cage_free: false,
    one_on_one_attention: true,
    online_booking: false,
    image_url: null,
    image_description: null,
    primary_city: 'San Diego',
    service_cities: ['San Diego', 'La Jolla', 'Chula Vista'],
    service_radius_miles: 18,
    created_at: now,
    updated_at: now,
  },
  {
    id: 5,
    slug: 'miami-grooming-express',
    name: 'Miami Grooming Express',
    full_address: '7250 Coral Way, Miami, FL 33155',
    city: 'Miami',
    state: 'FL',
    zip: '33155',
    phone: '(305) 555-0461',
    website: 'https://miamigroomingexpress.example.com',
    rating: 4.6,
    reviews_count: 203,
    google_maps_url: null,
    classification: 'mobile_pet_grooming',
    verification_confidence: 0.93,
    svc_full_groom: true,
    svc_bath_only: true,
    svc_nail_trim: true,
    svc_deshedding: true,
    svc_teeth_brushing: true,
    svc_ear_cleaning: true,
    svc_flea_treatment: true,
    svc_puppy_groom: false,
    svc_senior_groom: true,
    svc_dematting: true,
    svc_breed_cuts: true,
    accepts_dogs: true,
    accepts_cats: false,
    breed_sizes: ['small', 'medium', 'large', 'giant'],
    price_range_low: 50,
    price_range_high: 130,
    is_licensed: true,
    is_insured: true,
    fear_free_certified: false,
    years_experience: 10,
    uses_natural_products: false,
    cage_free: true,
    one_on_one_attention: true,
    online_booking: true,
    image_url: null,
    image_description: null,
    primary_city: 'Miami',
    service_cities: ['Miami', 'Miami Beach', 'Coral Gables', 'Hialeah'],
    service_radius_miles: 20,
    created_at: now,
    updated_at: now,
  },
  {
    id: 6,
    slug: 'tampa-bay-mobile-groomers',
    name: 'Tampa Bay Mobile Groomers',
    full_address: '4015 W Kennedy Blvd, Tampa, FL 33609',
    city: 'Tampa',
    state: 'FL',
    zip: '33609',
    phone: '(813) 555-0527',
    website: 'https://tampabaymobilegroomers.example.com',
    rating: 4.3,
    reviews_count: 67,
    google_maps_url: null,
    classification: 'mobile_pet_grooming',
    verification_confidence: 0.90,
    svc_full_groom: true,
    svc_bath_only: true,
    svc_nail_trim: true,
    svc_deshedding: true,
    svc_teeth_brushing: false,
    svc_ear_cleaning: false,
    svc_flea_treatment: false,
    svc_puppy_groom: true,
    svc_senior_groom: false,
    svc_dematting: false,
    svc_breed_cuts: true,
    accepts_dogs: true,
    accepts_cats: true,
    breed_sizes: ['small', 'medium', 'large'],
    price_range_low: 35,
    price_range_high: 85,
    is_licensed: false,
    is_insured: true,
    fear_free_certified: false,
    years_experience: 3,
    uses_natural_products: false,
    cage_free: false,
    one_on_one_attention: false,
    online_booking: true,
    image_url: null,
    image_description: null,
    primary_city: 'Tampa',
    service_cities: ['Tampa', 'St. Petersburg', 'Clearwater'],
    service_radius_miles: 22,
    created_at: now,
    updated_at: now,
  },
];
